import Head from "next/head";
import styles from "@/sass/layouts/home.module.scss";
import Header from "@/components/Header";
import Hero from "@/components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>ecosolution GREENERGY FOR LIFE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Group.png" />
      </Head>

      <main className={styles.main}>
        <Header />

        <Hero />
      </main>
    </>
  );
}
